apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-wp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-wp
    spec:
      containers:
      - name: wp-container
        image: wordpress:php7.0
        env:
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: db-password
        - name: WORDPRESS_DB_HOST
          value: blog-db-svc:8888        
        ports:
        - name: wp-port
          containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: blog-wp-svc
spec:
  ports:
  - port: 8888
    nodePort: 32002
    targetPort: wp-port
    protocol: TCP
  selector:
    app: blog-wp
  type: NodePort

